syncer:
  ack:
    flushPeriod: 100
  input:
    worker: 4
    max-retry: 5
    input-meta:
      last-run-metadata-dir: /tmp/syncer/meta/.last_position/

  filter:
    worker: 4

  output:
    worker: 2
    batch:
      worker: 2