syncer:
  input:
    worker: 4
    max-retry: 5
    mysql-masters:
      last_run_metadata_dir: /tmp/syncer/meta/.last_position/

  filter:
    worker: 2

  output:
    worker: 2
    batch:
      worker: 2